### ISSUE TITLE
Request to add links in Spanish (Latin America) language.

### ISSUE THREAD

**Issue by DallasBelt** [TheBeastLT/torrentio-scraper#94] opened 2022-12-27 18:21 UTC
Is it possible that the addon could scrape links in Latin American Spanish?

**Comment by TheBeastLT** [comment] 2022-12-27 20:54
Duplicate of #72

**Closed by TheBeastLT** 2022-12-27 20:54 UTC

**Comment by DallasBelt** [comment] 2023-02-12 16:04
I'm sorry to revive this issue, but #72 gives links in Spanish from Spain (Castellano). There is cinecalidad.run which contains links in Latin American Spanish (Mexico). Could it be possible to add it to Torrentio?

Thank you.
